In [2]:
import json
import os
import pandas as pd

In [84]:

# Folder path where your JSON files are stored
folder_path = 'D:\\MSBA\\GA\\'

# List to store all records from all files
all_data = []

# Loop through each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.json'):
        file_path = os.path.join(folder_path, filename)
        with open(file_path, 'r', encoding='utf-8') as file:
            for line in file:
                try:
                    all_data.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Skipping invalid line in {filename}:", e)

# Convert list of records to DataFrame
df = pd.DataFrame(all_data)

# Display results
print("Total records loaded:", len(df))

Total records loaded: 245209

In [85]:
df.head()

,event_date,event_timestamp,event_name,event_params,event_bundle_sequence_id,user_pseudo_id,privacy_info,user_properties,user_first_touch_timestamp,user_ltv,device,geo,traffic_source,stream_id,platform,ecommerce,items,event_value_in_usd
0,20210101,1609468318563156,first_visit,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN
1,20210101,1609468318563156,page_view,"[{'key': 'page_location', 'value': {'string_va...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN
2,20210101,1609468318563156,session_start,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN
3,20210101,1609468320458554,user_engagement,"[{'key': 'engaged_session_event', 'value': {'i...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN
4,20210101,1609468320458554,page_view,"[{'key': 'ga_session_id', 'value': {'int_value...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN

In [15]:
df.to_csv("GA_DATA.csv", index=False)

In [16]:
import os
print(os.getcwd())

C:\Users\Manas

In [86]:
df.dtypes

event_date                     object
event_timestamp                object
event_name                     object
event_params                   object
event_bundle_sequence_id       object
user_pseudo_id                 object
privacy_info                   object
user_properties                object
user_first_touch_timestamp     object
user_ltv                       object
device                         object
geo                            object
traffic_source                 object
stream_id                      object
platform                       object
ecommerce                      object
items                          object
event_value_in_usd            float64
dtype: object

In [87]:
df['datetime'] = pd.to_datetime(df['event_timestamp'], unit='us')

In [88]:
df.head()

,event_date,event_timestamp,event_name,event_params,event_bundle_sequence_id,user_pseudo_id,privacy_info,user_properties,user_first_touch_timestamp,user_ltv,device,geo,traffic_source,stream_id,platform,ecommerce,items,event_value_in_usd,datetime
0,20210101,1609468318563156,first_visit,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN,2021-01-01 02:31:58.563156
1,20210101,1609468318563156,page_view,"[{'key': 'page_location', 'value': {'string_va...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN,2021-01-01 02:31:58.563156
2,20210101,1609468318563156,session_start,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN,2021-01-01 02:31:58.563156
3,20210101,1609468320458554,user_engagement,"[{'key': 'engaged_session_event', 'value': {'i...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN,2021-01-01 02:32:00.458554
4,20210101,1609468320458554,page_view,"[{'key': 'ga_session_id', 'value': {'int_value...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}","{'category': 'desktop', 'mobile_brand_name': '...","{'continent': 'Europe', 'sub_continent': 'West...","{'medium': 'organic', 'name': '(organic)', 'so...",2100450278,WEB,{},[],NaN,2021-01-01 02:32:00.458554

In [96]:
df_1 = df.copy()

In [97]:
df_1.count()

event_date                    245209
event_timestamp               245209
event_name                    245209
event_params                  245209
event_bundle_sequence_id      245209
user_pseudo_id                245209
privacy_info                  245209
user_properties               245209
user_first_touch_timestamp    239861
user_ltv                      245209
device                        245209
geo                           245209
traffic_source                245209
stream_id                     245209
platform                      245209
ecommerce                     245209
items                         245209
event_value_in_usd               138
datetime                      245209
dtype: int64

In [98]:
# Extract multiple parameters at once in a more optimized way
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for param in event_params:
        key = param.get('key')
        if key in param_keys:
            value_dict = param.get('value', {})
            
            # Extract based on value type
            if 'string_value' in value_dict:
                results[key] = value_dict['string_value']
            elif 'int_value' in value_dict:
                results[key] = value_dict['int_value']
            elif 'float_value' in value_dict:
                results[key] = value_dict['float_value']
            elif 'double_value' in value_dict:
                results[key] = value_dict['double_value']
    
    return results

# Step 5: Define parameters we want to extract
params_to_extract = ['page_title', 'page_location', 'source', 'medium', 'ga_session_id', 'engagement_time_msec', 'session_engaged']

# Step 6: Apply the extraction function to each row
extracted_data = df_1['event_params'].apply(lambda x: extract_params(x, params_to_extract))

# Step 7: Convert the result to a DataFrame
params_df = pd.DataFrame(extracted_data.tolist())
print("Extracted parameters:")
print(params_df.head(3))
print("\n")

Extracted parameters:
             page_title                                      page_location  \
0  Google Dino Game Tee  https://shop.googlemerchandisestore.com/Google...
1  Google Dino Game Tee  https://shop.googlemerchandisestore.com/Google...
2  Google Dino Game Tee  https://shop.googlemerchandisestore.com/Google...

   source   medium ga_session_id engagement_time_msec session_engaged
0    None     None    3209612510                 None               1
1  google  organic    3209612510                 None               0
2    None     None    3209612510                 None            None

In [99]:
# Step 1: Define the parameters you want to extract
params_to_extract = ['continent', 'sub_continent', 'country', 'region', 'city', 'metro']

# Step 2: Define the extraction function
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for key in event_params:
        if key in param_keys:
            results[key] = event_params[key]
    
    return results

# Step 3: Apply the extraction function to the 'geo' column
extracted_data_geo = df_1['geo'].apply(lambda x: extract_params(x, params_to_extract) if isinstance(x, dict) else {})

# Step 4: Convert the result into a DataFrame
params_df_geo = pd.DataFrame(extracted_data_geo.tolist())

# Output the result
print("Extracted parameters Geo:")
print(params_df_geo.head(3))

Extracted parameters Geo:
  continent   sub_continent country                region       city  \
0    Europe  Western Europe  France  Auvergne-Rhone-Alpes  (not set)
1    Europe  Western Europe  France  Auvergne-Rhone-Alpes  (not set)
2    Europe  Western Europe  France  Auvergne-Rhone-Alpes  (not set)

       metro
0  (not set)
1  (not set)
2  (not set)

In [100]:
# Step 1: Define the parameters you want to extract
params_to_extract = ['category', 'mobile_brand_name', 'mobile_model_name', 'mobile_marketing_name', 'operating_system',
                     'operating_system_version', 'language', 'is_limited_ad_tracking', 'web_info']

# Step 2: Define the extraction function
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for key in event_params:
        if key in param_keys:
            results[key] = event_params[key]
    
    return results

# Step 3: Apply the extraction function to the 'geo' column
extracted_data_device = df_1['device'].apply(lambda x: extract_params(x, params_to_extract) if isinstance(x, dict) else {})

# Step 4: Convert the result into a DataFrame
params_df_device = pd.DataFrame(extracted_data_device.tolist())

# Output the result
print("Extracted parameters device:")
print(params_df_device.head(3))

Extracted parameters device:
  category mobile_brand_name mobile_model_name mobile_marketing_name  \
0  desktop         Microsoft           <Other>               <Other>
1  desktop         Microsoft           <Other>               <Other>
2  desktop         Microsoft           <Other>               <Other>

  operating_system operating_system_version language is_limited_ad_tracking  \
0          Windows               Windows 10    en-us                     No
1          Windows               Windows 10    en-us                     No
2          Windows               Windows 10    en-us                     No

                                            web_info
0  {'browser': '<Other>', 'browser_version': '<Ot...
1  {'browser': '<Other>', 'browser_version': '<Ot...
2  {'browser': '<Other>', 'browser_version': '<Ot...

In [101]:
# Step 1: Define the parameters you want to extract
params_to_extract = ['revenue', 'currency']

# Step 2: Define the extraction function
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for key in event_params:
        if key in param_keys:
            results[key] = event_params[key]
    
    return results

# Step 3: Apply the extraction function to the 'geo' column
extracted_data_rev = df_1['user_ltv'].apply(lambda x: extract_params(x, params_to_extract) if isinstance(x, dict) else {})

# Step 4: Convert the result into a DataFrame
params_df_rev = pd.DataFrame(extracted_data_rev.tolist())

# Output the result
print("Extracted parameters revenue:")
print(params_df_rev.head(3))

Extracted parameters revenue:
   revenue currency
0        0      USD
1        0      USD
2        0      USD

In [102]:
# Step 1: Define the parameters you want to extract
params_to_extract = ['medium', 'name', 'source']

# Step 2: Define the extraction function
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for key in event_params:
        if key in param_keys:
            results[key] = event_params[key]
    
    return results

# Step 3: Apply the extraction function to the 'geo' column
extracted_data_med = df_1['traffic_source'].apply(lambda x: extract_params(x, params_to_extract) if isinstance(x, dict) else {})

# Step 4: Convert the result into a DataFrame
params_df_med = pd.DataFrame(extracted_data_med.tolist())

# Output the result
print("Extracted parameters revenue:")
print(params_df_med.head(3))

Extracted parameters revenue:
    medium       name  source
0  organic  (organic)  google
1  organic  (organic)  google
2  organic  (organic)  google

In [103]:
# Step 1: Define the parameters you want to extract
params_to_extract = ['total_item_quantity', 'purchase_revenue_in_usd', 'tax_value_in_usd','unique_items','transaction_id']

# Step 2: Define the extraction function
def extract_params(event_params, param_keys):
    """Extract multiple parameters from event_params"""
    results = {key: None for key in param_keys}
    
    for key in event_params:
        if key in param_keys:
            results[key] = event_params[key]
    
    return results

# Step 3: Apply the extraction function to the 'geo' column
extracted_data_ecomm = df_1['ecommerce'].apply(lambda x: extract_params(x, params_to_extract) if isinstance(x, dict) else {})

# Step 4: Convert the result into a DataFrame
params_df_ecomm = pd.DataFrame(extracted_data_ecomm.tolist())

# Output the result
print("Extracted parameters revenue:")
print(params_df_ecomm.head(3))

Extracted parameters revenue:
  total_item_quantity  purchase_revenue_in_usd  tax_value_in_usd unique_items  \
0                None                      NaN               NaN         None
1                None                      NaN               NaN         None
2                None                      NaN               NaN         None

  transaction_id
0           None
1           None
2           None

In [104]:
df_1['item_ids'] = (df_1['items'].apply(lambda items: [item['item_id'] for item in items]).str[0])
df_1['item_name'] = (df_1['items'].apply(lambda items: [item['item_name'] for item in items]).str[0])
df_1['item_category'] = (df_1['items'].apply(lambda items: [item['item_category'] for item in items]).str[0])
print(df_1[['item_ids','item_name','item_category']])

         item_ids  item_name item_category
0             NaN        NaN           NaN
1             NaN        NaN           NaN
2             NaN        NaN           NaN
3             NaN        NaN           NaN
4             NaN        NaN           NaN
...           ...        ...           ...
245204  (not set)  (not set)     (not set)
245205  (not set)  (not set)     (not set)
245206  (not set)  (not set)     (not set)
245207  (not set)  (not set)     (not set)
245208  (not set)  (not set)     (not set)

[245209 rows x 3 columns]

In [105]:
df_2 = pd.concat([df_1,params_df,params_df_geo,params_df_device,params_df_rev,
                  params_df_med,params_df_ecomm], axis=1)
df_2.head()

,event_date,event_timestamp,event_name,event_params,event_bundle_sequence_id,user_pseudo_id,privacy_info,user_properties,user_first_touch_timestamp,user_ltv,...,revenue,currency,medium,name,source,total_item_quantity,purchase_revenue_in_usd,tax_value_in_usd,unique_items,transaction_id
0,20210101,1609468318563156,first_visit,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}",...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
1,20210101,1609468318563156,page_view,"[{'key': 'page_location', 'value': {'string_va...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}",...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
2,20210101,1609468318563156,session_start,"[{'key': 'ga_session_number', 'value': {'int_v...",1177212143,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}",...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
3,20210101,1609468320458554,user_engagement,"[{'key': 'engaged_session_event', 'value': {'i...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}",...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
4,20210101,1609468320458554,page_view,"[{'key': 'ga_session_id', 'value': {'int_value...",7525162155,1003046.9452926974,{'uses_transient_token': 'No'},[],1609468318563156,"{'revenue': 0, 'currency': 'USD'}",...,0,USD,organic,(organic),google,None,NaN,NaN,None,None

In [106]:
df_2.count()

event_date                    245209
event_timestamp               245209
event_name                    245209
event_params                  245209
event_bundle_sequence_id      245209
user_pseudo_id                245209
privacy_info                  245209
user_properties               245209
user_first_touch_timestamp    239861
user_ltv                      245209
device                        245209
geo                           245209
traffic_source                245209
stream_id                     245209
platform                      245209
ecommerce                     245209
items                         245209
event_value_in_usd               138
datetime                      245209
item_ids                       27393
item_name                      27393
item_category                  27393
page_title                    243950
page_location                 245209
source                         67364
medium                         67367
ga_session_id                 245209
engagement_time_msec          144147
session_engaged               222907
continent                     245209
sub_continent                 245209
country                       245209
region                        245209
city                          245209
metro                         245209
category                      245209
mobile_brand_name             245209
mobile_model_name             245209
mobile_marketing_name         245209
operating_system              245209
operating_system_version      245209
language                      151207
is_limited_ad_tracking        245209
web_info                      245209
revenue                       245209
currency                      245209
medium                        245209
name                          245209
source                        245209
total_item_quantity             3955
purchase_revenue_in_usd          144
tax_value_in_usd                 138
unique_items                   27393
transaction_id                 35760
dtype: int64

In [107]:
df_2.drop(columns=['event_params', 'device', 'geo','user_ltv','event_timestamp',
                   'traffic_source','privacy_info','user_properties','ecommerce','items'], inplace=True)

In [108]:
df_2.to_csv("GA_DATA.csv", index=False)
print(len(df_2.columns))
df_2.head()

44

,event_date,event_name,event_bundle_sequence_id,user_pseudo_id,user_first_touch_timestamp,stream_id,platform,event_value_in_usd,datetime,item_ids,...,revenue,currency,medium,name,source,total_item_quantity,purchase_revenue_in_usd,tax_value_in_usd,unique_items,transaction_id
0,20210101,first_visit,1177212143,1003046.9452926974,1609468318563156,2100450278,WEB,NaN,2021-01-01 02:31:58.563156,NaN,...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
1,20210101,page_view,1177212143,1003046.9452926974,1609468318563156,2100450278,WEB,NaN,2021-01-01 02:31:58.563156,NaN,...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
2,20210101,session_start,1177212143,1003046.9452926974,1609468318563156,2100450278,WEB,NaN,2021-01-01 02:31:58.563156,NaN,...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
3,20210101,user_engagement,7525162155,1003046.9452926974,1609468318563156,2100450278,WEB,NaN,2021-01-01 02:32:00.458554,NaN,...,0,USD,organic,(organic),google,None,NaN,NaN,None,None
4,20210101,page_view,7525162155,1003046.9452926974,1609468318563156,2100450278,WEB,NaN,2021-01-01 02:32:00.458554,NaN,...,0,USD,organic,(organic),google,None,NaN,NaN,None,None